use super::Orchestrator;
use super::helpers::*;
use crate::claude;
use crate::git;
use crate::runner;
use anyhow::Result;
use tracing::{info, warn};

impl Orchestrator {
    /// After each file, verifies no source code was modified, then commits the tests.
    pub(super) fn boost_coverage_to_threshold(&self, test_command: &str) -> Result<()> {
        let coverage_cmd = self.config.coverage_command.clone()
            .or_else(|| self.config.commands.coverage.clone())
            .or_else(|| runner::detect_coverage_command(&self.config.path));

        let cov_cmd = match coverage_cmd {
            Some(c) => c,
            None => {
                warn!("No coverage command available — skipping coverage gate. Set commands.coverage in YAML or use --coverage-command.");
                return Ok(());
            }
        };

        info!("=== Step 3b: Coverage boost (project: {:.0}%, per-file: {:.0}%) ===",
            self.config.min_coverage,
            self.config.min_file_coverage
        );

        // Initial coverage measurement
        let overall_pct = match self.run_coverage_and_measure(&cov_cmd) {
            Some(pct) => pct,
            None => {
                warn!("Could not measure project coverage — skipping coverage gate");
                return Ok(());
            }
        };

        // Get per-file coverage sorted ascending (least covered first)
        let lcov_path = match runner::find_lcov_report_with_hint(&self.config.path, self.config.commands.coverage_report.as_deref()) {
            Some(p) => p,
            None => {
                warn!("No lcov report found — cannot identify uncovered files");
                return Ok(());
            }
        };

        let file_coverages = runner::per_file_lcov_coverage(&lcov_path);

        // Build the list of files that need boosting:
        // 1. Files needed to reach overall min_coverage (sorted by coverage asc)
        // 2. Files below min_file_coverage threshold (regardless of overall %)
        let overall_needs_boost = overall_pct < self.config.min_coverage;
        let has_file_threshold = self.config.min_file_coverage > 0.0;

        let files_below_file_threshold: Vec<_> = if has_file_threshold {
            file_coverages.iter()
                .filter(|fc| fc.coverage_pct < self.config.min_file_coverage && !is_test_file(&fc.file))
                .collect()
        } else {
            Vec::new()
        };

        if !overall_needs_boost && files_below_file_threshold.is_empty() {
            color_info!(
                "Project-wide coverage {} meets {:.0}% and all files meet per-file threshold — no boost needed",
                cov_vs(overall_pct, self.config.min_coverage), self.config.min_coverage
            );
            return Ok(());
        }

        if overall_needs_boost {
            color_info!("Project-wide coverage {} is below {:.0}%", cov_prev(overall_pct), self.config.min_coverage);
        }
        if !files_below_file_threshold.is_empty() {
            info!("{} file(s) below per-file threshold of {:.0}%", files_below_file_threshold.len(), self.config.min_file_coverage);
        }

        // Merge both sets: files for overall boost + files below per-file threshold
        // Deduplicate and keep sorted by coverage ascending
        let files_needing_tests: Vec<_> = file_coverages.iter()
            .filter(|fc| {
                if is_test_file(&fc.file) {
                    return false;
                }
                if fc.coverage_pct >= 100.0 {
                    return false;
                }
                // Skip files matching user-configured exclusion patterns
                if !self.config.coverage_exclude.is_empty() {
                    if self.config.coverage_exclude.iter().any(|pat| {
                        glob::Pattern::new(pat).map(|p| p.matches(&fc.file)).unwrap_or(false)
                    }) {
                        return false;
                    }
                }
                // Skip files with 0 uncovered lines (rounding artifacts)
                if fc.total_lines <= fc.covered_lines {
                    return false;
                }
                // Include if needed for overall boost OR below per-file threshold
                overall_needs_boost || (has_file_threshold && fc.coverage_pct < self.config.min_file_coverage)
            })
            .collect();

        // Pre-filter: remove files that don't exist on disk (autogenerated classes, build artifacts)
        let (files_needing_tests, missing): (Vec<_>, Vec<_>) = files_needing_tests
            .into_iter()
            .partition(|fc| {
                let resolved = resolve_source_file(&self.config.path, &fc.file);
                resolved.exists()
            });

        if !missing.is_empty() {
            info!(
                "Skipping {} files not found on disk (autogenerated/build artifacts): {}{}",
                missing.len(),
                missing.iter().take(5).map(|f| f.file.as_str()).collect::<Vec<_>>().join(", "),
                if missing.len() > 5 { ", ..." } else { "" }
            );
        }

        // Log excluded patterns if any are configured
        if !self.config.coverage_exclude.is_empty() {
            let excluded_count = file_coverages.iter()
                .filter(|fc| {
                    self.config.coverage_exclude.iter().any(|pat| {
                        glob::Pattern::new(pat).map(|p| p.matches(&fc.file)).unwrap_or(false)
                    })
                })
                .count();
            if excluded_count > 0 {
                info!(
                    "Excluded {} file(s) from coverage boost matching patterns: {:?}",
                    excluded_count, self.config.coverage_exclude
                );
            }
        }

        if files_needing_tests.is_empty() {
            warn!("No source files with uncovered lines found in lcov report");
            return Ok(());
        }

        // Wave-based processing:
        //   parallel_size  = how many files to process per wave (AI generation only, no per-file tests)
        //   commit_size    = how many files per git commit (>= parallel_size, already resolved)
        //   skip_test_run  = true when parallel_size > 1 — defer test validation to wave time
        //   commit_immediately = true when commit_size <= parallel_size (one commit per wave)
        //
        // If commit_size > parallel_size, each wave creates a temp "reparo-wip:" commit and
        // every commit_size / parallel_size waves get squashed into one real commit.
        let parallel_size = self.config.coverage_wave_size as usize;
        let commit_size = self.config.coverage_commit_batch as usize; // already resolved (never 0)
        let skip_test_run = parallel_size > 1;
        let batch_mode = commit_size > 1 || skip_test_run;
        let commit_immediately = commit_size <= parallel_size;

        info!(
            "Found {} source files needing test coverage — generating tests starting from least covered{}",
            files_needing_tests.len(),
            if batch_mode {
                format!(" (wave size: {}, commit batch: {} files)", parallel_size, commit_size)
            } else {
                String::new()
            }
        );

        let test_examples = runner::find_test_examples(&self.config.path);
        let test_examples_str = test_examples.join("\n\n");
        let test_framework = test_command;

        // US-040: Build framework context once for all files in the boost loop
        let detected_deps = runner::detect_test_dependencies(&self.config.path);
        let framework_context_base = build_framework_context(
            &detected_deps,
            &self.config.test_generation,
        );

        let stash_prefix = "reparo-boost";

        let mut current_pct = overall_pct;
        let start_pct = overall_pct;
        let mut files_boosted = 0;
        let mut files_processed = 0usize;
        // Current wave accumulator (parallel_size files per wave)
        let mut current_wave: Vec<BoostFileResult> = Vec::new();
        // Temp "reparo-wip:" commits waiting to be squashed (when commit_size > parallel_size)
        let mut temp_commit_count = 0usize;
        let mut temp_commit_files: Vec<String> = Vec::new();
        let total_files = files_needing_tests.len();
        // Count of files actually queued/processed (for display)
        let mut queue_idx = 0;
        // Circuit breaker: stop after N consecutive wave failures (US-034)
        let mut consecutive_wave_failures = 0usize;
        let max_wave_failures = self.config.max_boost_failures;

        for (idx, fc) in files_needing_tests.iter().enumerate() {
            // Circuit breaker: stop if too many consecutive waves failed
            if max_wave_failures > 0 && consecutive_wave_failures >= max_wave_failures {
                warn!(
                    "Stopping coverage boost: {} consecutive waves failed — likely a systemic issue \
                     (e.g. missing test dependencies, Spring context not available). \
                     Processed {} files, {} committed, {} remaining. Fix test setup and re-run.",
                    consecutive_wave_failures, queue_idx, files_boosted, total_files - idx
                );
                break;
            }

            // Check if we can stop: overall threshold met AND this file doesn't need per-file boost
            let overall_met = current_pct >= self.config.min_coverage;
            let file_needs_boost = has_file_threshold && fc.coverage_pct < self.config.min_file_coverage;

            if overall_met && !file_needs_boost {
                continue; // Skip files that are only needed for overall boost
            }

            queue_idx += 1;
            let reason = if !overall_met && file_needs_boost {
                format!("overall {:.1}% < {:.0}% AND file {:.1}% < {:.0}%",
                    current_pct, self.config.min_coverage, fc.coverage_pct, self.config.min_file_coverage)
            } else if file_needs_boost {
                format!("file {:.1}% < per-file threshold {:.0}%", fc.coverage_pct, self.config.min_file_coverage)
            } else {
                format!("overall {:.1}% < {:.0}%", current_pct, self.config.min_coverage)
            };

            info!(
                "--- Coverage boost [{}/{}]: {} ({:.1}%, {}/{} lines) — {} | overall: {:.1}% ---",
                queue_idx,
                total_files,
                fc.file,
                fc.coverage_pct,
                fc.covered_lines,
                fc.total_lines,
                reason,
                current_pct
            );

            let is_last = idx == total_files - 1;

            files_processed += 1;
            match self.generate_tests_for_file(fc, test_framework, &test_examples_str, stash_prefix, skip_test_run, &framework_context_base, false)? {
                Some(result) if batch_mode && !result.test_files.is_empty() => {
                    // Wave mode: accumulate result, commit at wave boundary
                    current_wave.push(result);
                }
                Some(_) => {
                    // Individual mode (parallel=1, commit=1): already committed inside generate_tests_for_file
                    files_boosted += 1;
                    consecutive_wave_failures = 0;
                    match self.run_coverage_and_measure(&cov_cmd) {
                        Some(pct) => {
                            color_info!(
                                "Project-wide coverage after boost: {} (was {})",
                                cov_vs(pct, self.config.min_coverage), cov_prev(current_pct)
                            );
                            current_pct = pct;
                        }
                        None => {
                            warn!("Could not re-measure coverage — continuing with next file");
                        }
                    }
                }
                None => {
                    // File was skipped (excluded, too large, no uncovered lines, etc.)
                }
            }

            // Wave boundary: flush when wave is full or this is the last file
            let wave_ready = !current_wave.is_empty()
                && (current_wave.len() >= parallel_size || (is_last && !current_wave.is_empty()));

            if wave_ready {
                // Safety: ensure working tree is clean before wave commit
                // (stashes from the current wave are preserved — they'll be popped by commit_boost_batch)
                let _ = git::ensure_clean_state(&self.config.path);

                if commit_immediately {
                    // commit_size <= parallel_size: one real commit per wave
                    let committed = self.commit_boost_batch(&current_wave, test_framework, stash_prefix, skip_test_run, &framework_context_base)?;
                    files_boosted += committed;
                    current_wave.clear();
                    if committed > 0 {
                        consecutive_wave_failures = 0;
                        if let Some(pct) = self.run_coverage_and_measure(&cov_cmd) {
                            color_info!(
                                "Project-wide coverage after wave commit: {} (was {})",
                                cov_vs(pct, self.config.min_coverage), cov_prev(current_pct)
                            );
                            current_pct = pct;
                        }
                    } else {
                        consecutive_wave_failures += 1;
                        // Cleanup after failed wave: drop residual stashes and ensure clean state
                        let _ = git::stash_drop_matching(&self.config.path, stash_prefix);
                        let _ = git::ensure_clean_state(&self.config.path);
                    }
                    info!(
                        "Coverage boost progress: {}/{} files processed, {} committed, coverage: {:.1}% → {:.1}%",
                        files_processed, total_files, files_boosted, start_pct, current_pct
                    );
                } else {
                    // commit_size > parallel_size: create temp "reparo-wip:" commit, squash later
                    let (committed, wave_files) =
                        self.validate_and_temp_commit_wave(&current_wave, test_framework, stash_prefix, skip_test_run, &framework_context_base)?;
                    current_wave.clear();
                    if committed > 0 {
                        consecutive_wave_failures = 0;
                        // Only count as temp wip commit if wave_files is non-empty.
                        // Fallback per-file commits return empty wave_files (they're already real commits).
                        if !wave_files.is_empty() {
                            temp_commit_count += 1;
                            temp_commit_files.extend(wave_files);
                            // Re-measure so overall_met early-exit works and progress is accurate
                            if let Some(pct) = self.run_coverage_and_measure(&cov_cmd) {
                                color_info!(
                                    "Project-wide coverage after wave commit: {} (was {})",
                                    cov_vs(pct, self.config.min_coverage), cov_prev(current_pct)
                                );
                                current_pct = pct;
                            }
                        } else {
                            // Per-file fallback created real commits — re-measure coverage
                            if let Some(pct) = self.run_coverage_and_measure(&cov_cmd) {
                                color_info!(
                                    "Project-wide coverage after per-file fallback: {} (was {})",
                                    cov_vs(pct, self.config.min_coverage), cov_prev(current_pct)
                                );
                                current_pct = pct;
                            }
                        }
                        files_boosted += committed;
                    } else {
                        consecutive_wave_failures += 1;
                        // Cleanup after failed wave: drop residual stashes and ensure clean state
                        let _ = git::stash_drop_matching(&self.config.path, stash_prefix);
                        let _ = git::ensure_clean_state(&self.config.path);
                    }
                    info!(
                        "Coverage boost progress: {}/{} files processed, {} committed, coverage: {:.1}% → {:.1}%",
                        files_processed, total_files, files_boosted, start_pct, current_pct
                    );

                    // Squash boundary: when enough temp commits accumulated or last file
                    let squash_ready = temp_commit_files.len() >= commit_size
                        || (is_last && temp_commit_count > 0);
                    if squash_ready && temp_commit_count > 0 {
                        let _ = self.squash_boost_commits(temp_commit_count, &temp_commit_files);
                        temp_commit_count = 0;
                        temp_commit_files.clear();
                        if let Some(pct) = self.run_coverage_and_measure(&cov_cmd) {
                            color_info!(
                                "Project-wide coverage after squash commit: {} (was {})",
                                cov_vs(pct, self.config.min_coverage), cov_prev(current_pct)
                            );
                            current_pct = pct;
                        }
                    }
                }
            }
        }

        // Safety flush: handle any remaining wave entries not yet triggered by is_last
        // (can happen when all remaining files were skipped and the last real file already committed)
        if !current_wave.is_empty() {
            let committed = self.commit_boost_batch(&current_wave, test_framework, stash_prefix, skip_test_run, &framework_context_base)?;
            files_boosted += committed;
            current_wave.clear();
            if committed == 0 {
                let _ = git::stash_drop_matching(&self.config.path, stash_prefix);
                let _ = git::ensure_clean_state(&self.config.path);
            }
            if let Some(pct) = self.run_coverage_and_measure(&cov_cmd) {
                current_pct = pct;
            }
        }
        if temp_commit_count > 0 {
            let _ = self.squash_boost_commits(temp_commit_count, &temp_commit_files);
            if let Some(pct) = self.run_coverage_and_measure(&cov_cmd) {
                current_pct = pct;
            }
        }

        // Cleanup pass: files still below min_file_coverage get a targeted individual-mode retry.
        //
        // In wave mode (coverage_wave_size > 1), the main loop does only ONE round of test
        // generation per file (coverage_rounds is skipped — no per-file test run between rounds).
        // Files whose wave tests failed and were reverted end up never getting their full
        // coverage_rounds. This cleanup pass processes those files one-by-one with full
        // coverage_rounds support (force_individual = true).
        if has_file_threshold {
            let still_below: Vec<_> = runner::find_lcov_report_with_hint(
                    &self.config.path, self.config.commands.coverage_report.as_deref())
                .map(|p| runner::per_file_lcov_coverage(&p))
                .unwrap_or_default()
                .into_iter()
                .filter(|fc| {
                    !is_test_file(&fc.file)
                        && fc.coverage_pct < self.config.min_file_coverage
                        && fc.total_lines > fc.covered_lines
                        && !self.config.coverage_exclude.iter().any(|pat| {
                            glob::Pattern::new(pat).map(|p| p.matches(&fc.file)).unwrap_or(false)
                        })
                })
                .collect();

            if !still_below.is_empty() {
                info!(
                    "Cleanup pass: {} file(s) still below per-file threshold {:.0}% — retrying individually with up to {} round(s) each",
                    still_below.len(), self.config.min_file_coverage, self.config.coverage_rounds
                );
                for fc in &still_below {
                    match self.generate_tests_for_file(
                        fc, test_framework, &test_examples_str,
                        stash_prefix, false, &framework_context_base, true,
                    )? {
                        Some(_) => {
                            files_boosted += 1;
                            if let Some(pct) = self.run_coverage_and_measure(&cov_cmd) {
                                color_info!(
                                    "Project-wide coverage after cleanup commit: {} (was {})",
                                    cov_vs(pct, self.config.min_coverage), cov_prev(current_pct)
                                );
                                current_pct = pct;
                            }
                        }
                        None => {}
                    }
                }
            }
        }

        // Overall coverage retry pass: if overall coverage is still below min_coverage,
        // re-scan for files with room for improvement and retry them individually with
        // full coverage_rounds support.  The main wave loop only does one round per file,
        // so this pass compensates when the target hasn't been reached.
        if current_pct < self.config.min_coverage {
            let retry_candidates: Vec<_> = runner::find_lcov_report_with_hint(
                    &self.config.path, self.config.commands.coverage_report.as_deref())
                .map(|p| runner::per_file_lcov_coverage(&p))
                .unwrap_or_default()
                .into_iter()
                .filter(|fc| {
                    !is_test_file(&fc.file)
                        && fc.coverage_pct < 100.0
                        && fc.total_lines > fc.covered_lines
                        && !self.config.coverage_exclude.iter().any(|pat| {
                            glob::Pattern::new(pat).map(|p| p.matches(&fc.file)).unwrap_or(false)
                        })
                        && resolve_source_file(&self.config.path, &fc.file).exists()
                })
                .collect();

            if !retry_candidates.is_empty() {
                info!(
                    "Overall coverage retry: {:.1}% < {:.0}% target — retrying {} file(s) individually with up to {} round(s) each",
                    current_pct, self.config.min_coverage, retry_candidates.len(), self.config.coverage_rounds
                );
                for fc in &retry_candidates {
                    if current_pct >= self.config.min_coverage {
                        break;
                    }
                    match self.generate_tests_for_file(
                        &fc, test_framework, &test_examples_str,
                        stash_prefix, false, &framework_context_base, true,
                    )? {
                        Some(_) => {
                            files_boosted += 1;
                            if let Some(pct) = self.run_coverage_and_measure(&cov_cmd) {
                                color_info!(
                                    "Project-wide coverage after overall retry: {} (was {})",
                                    cov_vs(pct, self.config.min_coverage), cov_prev(current_pct)
                                );
                                current_pct = pct;
                            }
                        }
                        None => {}
                    }
                }
            }
        }

        // Final summary
        let remaining_below: Vec<_> = if has_file_threshold {
            // Re-read lcov to check which files are still below threshold
            runner::find_lcov_report_with_hint(&self.config.path, self.config.commands.coverage_report.as_deref())
                .map(|p| runner::per_file_lcov_coverage(&p))
                .unwrap_or_default()
                .into_iter()
                .filter(|fc| fc.coverage_pct < self.config.min_file_coverage && !is_test_file(&fc.file))
                .collect()
        } else {
            Vec::new()
        };

        color_info!(
            "Coverage boost summary: processed {} files, committed {}, coverage {:.1}% → {:.1}% (target: {:.0}%)",
            files_processed, files_boosted, start_pct, current_pct, self.config.min_coverage
        );
        if current_pct >= self.config.min_coverage && remaining_below.is_empty() {
            color_info!(
                "Coverage boost complete: {} (target {:.0}%) — {} files boosted",
                cov_vs(current_pct, self.config.min_coverage), self.config.min_coverage, files_boosted
            );
        } else {
            if current_pct < self.config.min_coverage {
                color_info!(
                    "⚠ Coverage boost: overall {} still below target {:.0}%",
                    cov_vs(current_pct, self.config.min_coverage), self.config.min_coverage
                );
            }
            if !remaining_below.is_empty() {
                warn!(
                    "{} file(s) still below per-file threshold {:.0}%:",
                    remaining_below.len(), self.config.min_file_coverage
                );
                for fc in &remaining_below {
                    warn!("  {} — {:.1}%", fc.file, fc.coverage_pct);
                }
            }
            warn!("{} files boosted. Continuing with fixes anyway.", files_boosted);
        }

        Ok(())
    }

    /// Generate tests for a single file in a multi-round loop until the
    /// coverage threshold is met or the maximum rounds are exhausted.
    ///
    /// `coverage_rounds` (from config):
    ///   - N > 0 → at most N rounds per file
    ///   - 0     → unlimited rounds, keep going while coverage still improves
    ///
    /// Generate tests for a single file in a multi-round loop.
    ///
    /// When `coverage_commit_batch == 1`, commits per round (original behavior).
    /// When `coverage_commit_batch > 1`, accumulates test files and stashes them
    /// for later batch commit by `commit_boost_batch()`.
    ///
    /// Returns `Some(BoostFileResult)` if tests were generated, `None` if skipped.
    fn generate_tests_for_file(
        &self,
        fc: &runner::FileCoverage,
        test_framework: &str,
        test_examples_str: &str,
        stash_prefix: &str,
        skip_test_run: bool,
        framework_context: &str,
        // When true: ignore coverage_commit_batch and wave mode — commit each round immediately
        // and run tests after each round (enables full coverage_rounds support).
        // Used by the cleanup pass for files still below min_file_coverage after the main wave loop.
        force_individual: bool,
    ) -> Result<Option<BoostFileResult>> {
        // Skip files matching user-configured exclusion patterns (safety net)
        if !self.config.coverage_exclude.is_empty() {
            if self.config.coverage_exclude.iter().any(|pat| {
                glob::Pattern::new(pat).map(|p| p.matches(&fc.file)).unwrap_or(false)
            }) {
                info!("Skipping excluded file: {}", fc.file);
                return Ok(None);
            }
        }

        // Skip files with 0 uncovered lines — nothing to boost
        if fc.total_lines <= fc.covered_lines {
            info!("File {} has 0 uncovered lines — nothing to boost", fc.file);
            return Ok(None);
        }

        // Read the source file — try direct path first, then common source roots
        let full_path = resolve_source_file(&self.config.path, &fc.file);
        let source_content = match std::fs::read_to_string(&full_path) {
            Ok(c) => c,
            Err(e) => {
                warn!("Cannot read {} (resolved to {}): {} — skipping", fc.file, full_path.display(), e);
                return Ok(None);
            }
        };

        let batch_mode = if force_individual {
            false
        } else {
            self.config.coverage_commit_batch > 1 || skip_test_run
        };
        let skip_test_run = if force_individual { false } else { skip_test_run };
        let max_rounds = self.config.coverage_rounds;
        let unlimited = max_rounds == 0;
        let mut round: u32 = 0;
        let mut any_success = false;
        let mut previous_coverage_pct = fc.coverage_pct;
        let mut current_uncovered_count = fc.total_lines.saturating_sub(fc.covered_lines);
        // Track specific uncovered line numbers across rounds for targeted prompts.
        let mut current_uncovered_lines: Vec<u32> = fc.uncovered_lines.clone();
        let mut last_test_output = String::new();
        let mut accumulated_test_files: Vec<String> = Vec::new();
        let mut accumulated_artifacts: Vec<String> = Vec::new();

        loop {
            round += 1;

            // Check round limit (0 = unlimited)
            if !unlimited && round > max_rounds {
                info!(
                    "Reached max coverage rounds ({}) for {} — coverage at {:.1}%",
                    max_rounds, fc.file, previous_coverage_pct
                );
                break;
            }

            // Safety cap for unlimited mode — prevent truly infinite loops
            if unlimited && round > 50 {
                warn!("Safety cap: 50 rounds reached for {} — stopping", fc.file);
                break;
            }

            let round_label = if unlimited {
                format!("round {} (unlimited)", round)
            } else {
                format!("round {}/{}", round, max_rounds)
            };

            info!(
                "Coverage boost {} for {} — current {:.1}%, {} uncovered lines",
                round_label, fc.file, previous_coverage_pct, current_uncovered_count
            );

            // Decide strategy: chunked (method-by-method) or single prompt
            let use_chunks = current_uncovered_lines.len() > 15;

            let file_class = runner::classify_source_file(&fc.file, &self.config.path);
            let pkg_hint = runner::derive_test_package(&fc.file)
                .map(|p| format!("The test class should be in package `{}` under `src/test/java/`.", p))
                .unwrap_or_default();
            let per_file_ctx = if round == 1 {
                build_per_file_context(framework_context, &file_class, &pkg_hint)
            } else {
                build_per_file_context(framework_context, &file_class, "")
            };

            if use_chunks {
                // --- Chunked strategy: one AI call per method/block ---
                let chunks = split_into_method_chunks(&source_content, &current_uncovered_lines, &fc.file);
                let total_chunks = chunks.len();
                info!(
                    "Splitting {} uncovered lines into {} method chunk(s) for {} ({})",
                    current_uncovered_lines.len(), total_chunks, fc.file, round_label
                );

                for (ci, chunk) in chunks.iter().enumerate() {
                    let chunk_idx = ci + 1;
                    let chunk_tier = claude::classify_test_gen_tier(
                        chunk.uncovered_count,
                        chunk.snippet.lines().count(),
                    );

                    let prompt = claude::build_chunk_test_prompt(
                        &fc.file,
                        &chunk.label,
                        &chunk.snippet,
                        chunk_idx,
                        total_chunks,
                        test_framework,
                        &per_file_ctx,
                    );

                    if self.config.show_prompts {
                        info!("Chunk {}/{} prompt ({}):\n{}", chunk_idx, total_chunks, round_label, prompt);
                    }

                    info!(
                        "  Chunk {}/{}: {} — {} uncovered lines [{}]",
                        chunk_idx, total_chunks, chunk.label, chunk.uncovered_count, chunk_tier
                    );
                    match self.run_ai(&prompt, &chunk_tier) {
                        Ok(_) => {
                            info!("  Chunk {}/{} completed", chunk_idx, total_chunks);
                            // Validate: no source files modified by this chunk
                            let changed = git::changed_files(&self.config.path).unwrap_or_default();
                            let src_modified: Vec<&String> = changed.iter()
                                .filter(|f| !is_test_file(f) && !is_generated_artifact(f) && !is_internal_file(f))
                                .collect();
                            if !src_modified.is_empty() {
                                warn!("  Chunk {}/{} modified source files: {:?} — reverting chunk", chunk_idx, total_chunks, src_modified);
                                let _ = git::revert_changes(&self.config.path);
                                // Continue with next chunk — don't abort the whole file
                            } else {
                                // Stage test files from this chunk to preserve them across subsequent chunks
                                let test_files: Vec<String> = changed.iter()
                                    .filter(|f| is_test_file(f) || is_generated_artifact(f))
                                    .cloned()
                                    .collect();
                                if !test_files.is_empty() {
                                    let refs: Vec<&str> = test_files.iter().map(|s| s.as_str()).collect();
                                    let _ = git::add_files(&self.config.path, &refs);
                                    // Revert non-test changes
                                    let _ = git::revert_changes(&self.config.path);
                                }
                            }
                        }
                        Err(e) => {
                            warn!(
                                "  Chunk {}/{} ({}) failed: {} — skipping chunk",
                                chunk_idx, total_chunks, chunk.label, e
                            );
                            let _ = git::revert_changes(&self.config.path);
                            // Continue with remaining chunks
                        }
                    }
                }

                // Check if any test files were generated across all chunks
                let has_staged = git::has_staged_changes(&self.config.path).unwrap_or(false);
                let all_changed = git::changed_files(&self.config.path).unwrap_or_default();
                if all_changed.is_empty() && !has_staged {
                    warn!("No test files generated across all chunks for {} ({})", fc.file, round_label);
                    break;
                }
            } else {
                // --- Single-prompt strategy: ≤15 uncovered lines ---
                let covered_count = fc.total_lines.saturating_sub(current_uncovered_count as u64);
                let uncovered_summary = format!(
                    "{:.1}% coverage — {} of {} coverable lines hit, {} uncovered",
                    previous_coverage_pct, covered_count, fc.total_lines, current_uncovered_count
                );
                let uncovered_snippets = extract_uncovered_snippets(
                    &source_content,
                    &current_uncovered_lines,
                    80,
                );

                let prompt = if round == 1 {
                    claude::build_test_generation_prompt(
                        &fc.file,
                        &uncovered_summary,
                        &uncovered_snippets,
                        test_framework,
                        test_examples_str,
                        &per_file_ctx,
                    )
                } else {
                    claude::build_test_generation_retry_prompt(
                        &fc.file,
                        &uncovered_summary,
                        &uncovered_snippets,
                        test_framework,
                        round,
                        &truncate(&last_test_output, 1000),
                        &per_file_ctx,
                    )
                };

                if self.config.show_prompts {
                    info!("Coverage boost prompt ({}):\n{}", round_label, prompt);
                }

                let uncovered = current_uncovered_count as usize;
                let test_tier = claude::classify_test_gen_tier(uncovered, fc.total_lines as usize);
                info!("Generating tests for {} [{}] ({})...", fc.file, test_tier, round_label);
                match self.run_ai(&prompt, &test_tier) {
                    Ok(_) => {
                        info!("AI completed test generation for {} ({})", fc.file, round_label);
                    }
                    Err(e) => {
                        warn!("Failed to generate tests for {} ({}): {} — stopping rounds", fc.file, round_label, e);
                        let _ = git::revert_changes(&self.config.path);
                        break;
                    }
                }
            }

            // Verify no source files were modified
            let changed = match git::changed_files(&self.config.path) {
                Ok(f) => f,
                Err(e) => {
                    warn!("Cannot check changed files: {} — reverting", e);
                    let _ = git::revert_changes(&self.config.path);
                    break;
                }
            };

            if changed.is_empty() {
                warn!("No files changed in {} for {} — stopping rounds", round_label, fc.file);
                break;
            }

            let source_files_modified: Vec<&String> = changed.iter()
                .filter(|f| !is_test_file(f) && !is_generated_artifact(f) && !is_internal_file(f))
                .collect();

            if !source_files_modified.is_empty() {
                warn!(
                    "Source files were modified during test generation for {} ({}): {:?} — reverting",
                    fc.file, round_label, source_files_modified
                );
                let _ = git::revert_changes(&self.config.path);
                break;
            }

            // Run tests (skipped when skip_test_run=true — validation happens at wave commit time)
            if !skip_test_run {
                info!("Running tests to validate generated tests ({})...", round_label);
                match runner::run_tests(&self.config.path, test_framework, self.config.test_timeout) {
                    Ok((true, output)) => {
                        info!("Tests pass after {} for {}", round_label, fc.file);
                        last_test_output = output;
                    }
                    Ok((false, output)) => {
                        warn!("Tests FAIL after {} for {} — reverting:\n{}", round_label, fc.file, runner::extract_error_summary(&output, 500));
                        last_test_output = output;
                        let _ = git::revert_changes(&self.config.path);
                        // Don't break — try again next round if rounds remain
                        continue;
                    }
                    Err(e) => {
                        warn!("Test execution error in {} for {} — reverting: {}", round_label, fc.file, e);
                        let _ = git::revert_changes(&self.config.path);
                        break;
                    }
                }
            } else {
                info!("Skipping per-file test run for {} ({}) — deferred to wave validation", fc.file, round_label);
            }

            // Identify test files and artifacts
            let test_files_changed: Vec<String> = changed.iter()
                .filter(|f| is_test_file(f))
                .cloned()
                .collect();

            if test_files_changed.is_empty() {
                let _ = git::revert_changes(&self.config.path);
                break;
            }

            let generated_artifacts: Vec<String> = changed.iter()
                .filter(|f| is_generated_artifact(f))
                .cloned()
                .collect();

            // Track extra files (helpers, fixtures, configs) that AI may have created
            // These are neither test files, nor known artifacts, nor the source file itself
            let extra_files: Vec<String> = changed.iter()
                .filter(|f| !is_test_file(f) && !is_generated_artifact(f) && !is_internal_file(f) && **f != fc.file)
                .cloned()
                .collect();
            if !extra_files.is_empty() {
                info!("Tracking {} extra generated file(s) for {}: {:?}", extra_files.len(), fc.file, extra_files);
            }

            if batch_mode {
                // Batch mode: accumulate test files, don't commit yet
                accumulated_test_files.extend(test_files_changed.clone());
                accumulated_artifacts.extend(generated_artifacts.clone());
                accumulated_artifacts.extend(extra_files.clone());
                any_success = true;

                // Stage test files + artifacts + extra files to keep them across rounds within the same file
                let mut stage_refs: Vec<&str> = test_files_changed.iter().map(|s| s.as_str()).collect();
                stage_refs.extend(generated_artifacts.iter().map(|s| s.as_str()));
                stage_refs.extend(extra_files.iter().map(|s| s.as_str()));
                if let Err(e) = git::add_files(&self.config.path, &stage_refs) {
                    warn!("Failed to stage test files: {} — reverting", e);
                    let _ = git::revert_changes(&self.config.path);
                    break;
                }

                // Revert non-test leftover changes, keep staged test files + artifacts
                let _ = git::revert_changes(&self.config.path);

                info!("Staged tests for {} ({}) — deferred commit", fc.file, round_label);
            } else {
                // Individual mode: commit immediately (original behavior)
                let refs: Vec<&str> = test_files_changed.iter().map(|s| s.as_str()).collect();
                if let Err(e) = git::add_files(&self.config.path, &refs) {
                    warn!("Failed to stage test files: {} — reverting", e);
                    let _ = git::revert_changes(&self.config.path);
                    break;
                }

                // Revert non-test, non-artifact leftover changes before committing
                let _ = git::revert_changes(&self.config.path);
                // Re-stage generated artifacts so they don't show as dirty
                if !generated_artifacts.is_empty() {
                    let artifact_refs: Vec<&str> = generated_artifacts.iter().map(|s| s.as_str()).collect();
                    let _ = git::add_files(&self.config.path, &artifact_refs);
                }

                let commit_msg = format_commit_message(
                    &self.config, "test", "coverage",
                    &format!("add tests for {} ({:.0}% → boost, {})", fc.file, previous_coverage_pct, round_label),
                    "", "", &fc.file,
                );
                if let Err(e) = git::commit(&self.config.path, &commit_msg) {
                    warn!("Failed to commit tests for {} ({}): {} — reverting", fc.file, round_label, e);
                    let _ = git::revert_changes(&self.config.path);
                    break;
                }

                info!("Committed tests for {} ({})", fc.file, round_label);
                any_success = true;

                // Revert any remaining leftover changes
                let _ = git::revert_changes(&self.config.path);
            }

            // Re-measure file coverage to decide if we need another round.
            // Skipped when skip_test_run=true because tests haven't run yet — we only
            // do one round per file in wave mode and let the wave commit validate coverage.
            if !skip_test_run {
                let coverage_cmd = self.config.coverage_command.clone()
                    .or_else(|| self.config.commands.coverage.clone())
                    .or_else(|| runner::detect_coverage_command(&self.config.path));
                if let Some(ref cov_cmd) = coverage_cmd {
                    let _ = runner::run_shell_command(&self.config.path, cov_cmd, "coverage");
                }

                let lcov_path = runner::find_lcov_report_with_hint(
                    &self.config.path,
                    self.config.commands.coverage_report.as_deref(),
                );
                if let Some(ref lcov) = lcov_path {
                    let file_coverages = runner::per_file_lcov_coverage(lcov);
                    if let Some(updated_fc) = file_coverages.iter().find(|f| f.file == fc.file) {
                        let new_pct = updated_fc.coverage_pct;
                        let new_uncovered = updated_fc.total_lines.saturating_sub(updated_fc.covered_lines);
                        color_info!(
                            "Coverage for {} after {}: {:.1}% → {:.1}% ({} uncovered lines remaining)",
                            fc.file, round_label, previous_coverage_pct, new_pct, new_uncovered
                        );

                        // Check if threshold met
                        let threshold = if self.config.min_file_coverage > 0.0 {
                            self.config.min_file_coverage
                        } else {
                            self.config.min_coverage
                        };

                        if new_pct >= threshold {
                            color_info!(
                                "Coverage threshold {:.0}% met for {} — done after {} round(s)",
                                threshold, fc.file, round
                            );
                            break;
                        }

                        // In unlimited mode: stop if no improvement
                        if unlimited && new_pct <= previous_coverage_pct {
                            info!(
                                "No coverage improvement for {} ({:.1}% → {:.1}%) — stopping rounds",
                                fc.file, previous_coverage_pct, new_pct
                            );
                            break;
                        }

                        previous_coverage_pct = new_pct;
                        current_uncovered_count = new_uncovered;
                        current_uncovered_lines = updated_fc.uncovered_lines.clone();
                    } else {
                        warn!("File {} not found in lcov after {} — stopping rounds", fc.file, round_label);
                        break;
                    }
                } else {
                    // No lcov report — can't measure progress, stop looping
                    warn!("No lcov report found after {} — cannot verify improvement, stopping", round_label);
                    break;
                }
            } else {
                // In wave mode: one round of test generation per file is enough.
                // The wave commit will validate and measure coverage for all files together.
                break;
            }
        }

        if !any_success {
            return Ok(None);
        }

        // In batch mode, stash accumulated test files + artifacts for later batch commit
        if batch_mode && !accumulated_test_files.is_empty() {
            let stash_msg = format!("{}:{}", stash_prefix, fc.file);
            let mut refs: Vec<&str> = accumulated_test_files.iter().map(|s| s.as_str()).collect();
            refs.extend(accumulated_artifacts.iter().map(|s| s.as_str()));
            // Ensure all test files + artifacts are staged before stashing
            let _ = git::add_files(&self.config.path, &refs);
            match git::stash_push(&self.config.path, &stash_msg, &refs) {
                Ok(()) => {
                    info!("Stashed {} test files for {} — pending batch commit", accumulated_test_files.len(), fc.file);
                }
                Err(e) => {
                    warn!("Failed to stash test files for {}: {} — committing individually", fc.file, e);
                    // Fallback: commit now
                    let commit_msg = format_commit_message(
                        &self.config, "test", "coverage",
                        &format!("add tests for {} ({:.0}% → boost)", fc.file, fc.coverage_pct),
                        "", "", &fc.file,
                    );
                    let _ = git::commit(&self.config.path, &commit_msg);
                }
            }
            let _ = git::revert_changes(&self.config.path);
        }

        Ok(Some(BoostFileResult {
            file: fc.file.clone(),
            test_files: accumulated_test_files,
            artifacts: accumulated_artifacts,
            rounds_completed: round.saturating_sub(1),
            coverage_before: fc.coverage_pct,
        }))
    }

    /// Commit a batch of boost results atomically.
    ///
    /// Pops stashed test files, optionally runs tests to validate all pass together,
    /// and creates a single commit. `run_tests` should be `true` when per-file test
    /// runs were skipped (i.e. `skip_test_run = true`). Falls back gracefully on failure.
    fn commit_boost_batch(
        &self,
        batch: &[BoostFileResult],
        test_framework: &str,
        stash_prefix: &str,
        run_tests: bool,
        framework_context: &str,
    ) -> Result<usize> {
        if batch.is_empty() {
            return Ok(0);
        }

        info!(
            "Committing batch of {} file(s): {}",
            batch.len(),
            batch.iter().map(|r| r.file.as_str()).collect::<Vec<_>>().join(", ")
        );

        // Pop all stashes from the batch (restores test files)
        let popped = git::stash_pop_matching(&self.config.path, stash_prefix)?;
        if popped == 0 {
            warn!("No stashes found for batch commit — nothing to commit");
            return Ok(0);
        }

        // Optionally run tests to validate all batch test files together.
        // Skipped when tests were already validated per-file (run_tests=false).
        if run_tests {
            // Build/compile before running tests (fast failure on compilation errors)
            let build_cmd = self.config.commands.test_compile.as_ref()
                .or(self.config.commands.build.as_ref());
            if let Some(cmd) = build_cmd {
                match runner::run_shell_command(&self.config.path, cmd, "test-compile") {
                    Ok((true, _)) => {
                        info!("Pre-test build succeeded for batch ({} files)", batch.len());
                    }
                    Ok((false, output)) => {
                        warn!(
                            "Pre-test build failed for {} files — falling back to per-file validation:\n{}",
                            batch.len(), runner::extract_error_summary(&output, 800)
                        );
                        return Ok(self.fallback_per_file_commit(batch, test_framework, framework_context));
                    }
                    Err(e) => {
                        warn!("Pre-test build error during batch commit: {} — falling back to per-file validation", e);
                        return Ok(self.fallback_per_file_commit(batch, test_framework, framework_context));
                    }
                }
            }

            match runner::run_tests(&self.config.path, test_framework, self.config.test_timeout) {
                Ok((true, _)) => {
                    info!("Wave tests pass — proceeding with batch commit ({} files)", batch.len());
                }
                Ok((false, output)) => {
                    warn!(
                        "Batch tests failed for {} files — falling back to per-file validation:\n{}",
                        batch.len(), runner::extract_error_summary(&output, 800)
                    );
                    // Files are in the working tree (stashes already popped).
                    // Try each file individually instead of discarding all.
                    return Ok(self.fallback_per_file_commit(batch, test_framework, framework_context));
                }
                Err(e) => {
                    warn!("Test execution error during batch commit: {} — falling back to per-file validation", e);
                    return Ok(self.fallback_per_file_commit(batch, test_framework, framework_context));
                }
            }
        }

        // Unstage everything (stash_pop_matching stages between applies),
        // then selectively re-stage only test files + artifacts.
        let _ = git::reset_index(&self.config.path);
        let mut all_stage_files: Vec<&str> = batch.iter()
            .flat_map(|r| r.test_files.iter().map(|s| s.as_str()))
            .collect();
        all_stage_files.extend(batch.iter().flat_map(|r| r.artifacts.iter().map(|s| s.as_str())));
        if let Err(e) = git::add_files(&self.config.path, &all_stage_files) {
            warn!("Failed to stage batch test files: {}", e);
            let _ = git::revert_changes(&self.config.path);
            return Ok(0);
        }
        let _ = git::revert_changes(&self.config.path); // clean remaining leftovers

        let file_list: Vec<&str> = batch.iter().map(|r| r.file.as_str()).collect();
        let msg = if batch.len() == 1 {
            format_commit_message(
                &self.config, "test", "coverage",
                &format!("add tests for {} ({:.0}% → boost)", batch[0].file, batch[0].coverage_before),
                "", "", &batch[0].file,
            )
        } else {
            format_commit_message(
                &self.config, "test", "coverage",
                &format!("add tests for {} files ({})", batch.len(), file_list.join(", ")),
                "", "", "",
            )
        };
        match git::commit(&self.config.path, &msg) {
            Ok(()) => {
                info!("Batch commit successful ({} files)", batch.len());
                Ok(batch.len())
            }
            Err(e) => {
                warn!("Batch commit failed: {} — reverting", e);
                let _ = git::revert_changes(&self.config.path);
                Ok(0)
            }
        }
    }

    /// Fallback when wave tests fail: re-stash each file's changes individually,
    /// then test and commit them one by one. Returns the number of files committed.
    ///
    /// Expects the working tree to contain all popped stash files (from the failed wave).
    fn fallback_per_file_commit(
        &self,
        batch: &[BoostFileResult],
        test_framework: &str,
        framework_context: &str,
    ) -> usize {
        let retry_prefix = "reparo-retry";
        warn!("Falling back to per-file validation for {} file(s)", batch.len());

        // Re-stash each file's changes individually so we can test them one by one.
        for result in batch {
            let mut refs: Vec<&str> = result.test_files.iter().map(|s| s.as_str()).collect();
            refs.extend(result.artifacts.iter().map(|s| s.as_str()));
            if refs.is_empty() {
                continue;
            }
            let stash_msg = format!("{}:{}", retry_prefix, result.file);
            let _ = git::add_files(&self.config.path, &refs);
            if let Err(e) = git::stash_push(&self.config.path, &stash_msg, &refs) {
                warn!("Failed to re-stash files for {}: {} — skipping", result.file, e);
            }
        }
        // Clean anything left over from the failed wave
        let _ = git::revert_changes(&self.config.path);

        let mut committed = 0usize;
        for result in batch {
            if result.test_files.is_empty() {
                continue;
            }
            let match_str = format!("{}:{}", retry_prefix, result.file);

            let popped = match git::stash_pop_matching(&self.config.path, &match_str) {
                Ok(n) => n,
                Err(e) => {
                    warn!("Failed to pop retry stash for {}: {} — skipping", result.file, e);
                    let _ = git::stash_drop_matching(&self.config.path, &match_str);
                    let _ = git::revert_changes(&self.config.path);
                    continue;
                }
            };
            if popped == 0 {
                warn!("No retry stash found for {} — skipping", result.file);
                continue;
            }

            // Build/compile before running tests (fast failure on compilation errors)
            let build_cmd = self.config.commands.test_compile.as_ref()
                .or(self.config.commands.build.as_ref());
            if let Some(cmd) = build_cmd {
                match runner::run_shell_command(&self.config.path, cmd, "test-compile") {
                    Ok((true, _)) => {
                        info!("Per-file build succeeded for {}", result.file);
                    }
                    Ok((false, output)) => {
                        warn!(
                            "Per-file build failed for {} — {}:\n{}",
                            result.file,
                            if self.config.retry_failed_wave_files { "will retry with error context" } else { "discarding" },
                            runner::extract_error_summary(&output, 800)
                        );
                        let _ = git::revert_changes(&self.config.path);
                        if self.config.retry_failed_wave_files {
                            if self.retry_failed_file_with_context(result, test_framework, &output, framework_context) {
                                committed += 1;
                            }
                        }
                        continue;
                    }
                    Err(e) => {
                        warn!("Build error for {} — discarding: {}", result.file, e);
                        let _ = git::revert_changes(&self.config.path);
                        continue;
                    }
                }
            }

            // Run tests with just this file's changes
            match runner::run_tests(&self.config.path, test_framework, self.config.test_timeout) {
                Ok((true, _)) => {
                    info!("Per-file tests pass for {} — committing", result.file);
                    let mut stage_refs: Vec<&str> = result.test_files.iter().map(|s| s.as_str()).collect();
                    stage_refs.extend(result.artifacts.iter().map(|s| s.as_str()));
                    if git::add_files(&self.config.path, &stage_refs).is_ok() {
                        let _ = git::revert_changes(&self.config.path); // clean non-test leftovers
                        let msg = format_commit_message(
                            &self.config, "test", "coverage",
                            &format!("add tests for {} ({:.0}% → boost)", result.file, result.coverage_before),
                            "", "", &result.file,
                        );
                        if git::commit(&self.config.path, &msg).is_ok() {
                            committed += 1;
                        } else {
                            warn!("Commit failed for {} — reverting", result.file);
                            let _ = git::revert_changes(&self.config.path);
                        }
                    } else {
                        warn!("Failed to stage files for {} — reverting", result.file);
                        let _ = git::revert_changes(&self.config.path);
                    }
                }
                Ok((false, output)) => {
                    warn!(
                        "Per-file tests fail for {} — {}:\n{}",
                        result.file,
                        if self.config.retry_failed_wave_files { "will retry with error context" } else { "discarding" },
                        runner::extract_error_summary(&output, 800)
                    );
                    let _ = git::revert_changes(&self.config.path);
                    if self.config.retry_failed_wave_files {
                        if self.retry_failed_file_with_context(result, test_framework, &output, framework_context) {
                            committed += 1;
                        }
                    }
                }
                Err(e) => {
                    warn!("Test error for {} — discarding: {}", result.file, e);
                    let _ = git::revert_changes(&self.config.path);
                }
            }
        }

        // Safety cleanup: drop any remaining retry stashes
        let _ = git::stash_drop_matching(&self.config.path, retry_prefix);

        if committed > 0 {
            info!("Per-file fallback: committed {} of {} file(s)", committed, batch.len());
        } else {
            warn!("Per-file fallback: no files passed individual validation");
        }
        committed
    }

    /// Retry test generation for a single file that failed build/test in per-file fallback.
    ///
    /// Calls the AI with the previous error as context, validates the new tests
    /// (build + test), and commits if successful. Returns `true` if committed.
    fn retry_failed_file_with_context(
        &self,
        result: &BoostFileResult,
        test_framework: &str,
        error_output: &str,
        framework_context: &str,
    ) -> bool {
        info!("Retrying test generation for {} with compilation error context", result.file);

        let uncovered_summary = format!(
            "{:.0}% coverage — previous test generation attempt failed. \
             Fix the errors and regenerate working tests.",
            result.coverage_before
        );
        // Repair retry: the AI already generated tests that failed to compile.
        // No snippets needed — the error output tells it what to fix.
        let uncovered_snippets = String::new();
        // US-040: Include framework context in retry
        let file_class = runner::classify_source_file(&result.file, &self.config.path);
        let per_file_ctx = build_per_file_context(framework_context, &file_class, "");
        let prompt = claude::build_test_generation_retry_prompt(
            &result.file,
            &uncovered_summary,
            &uncovered_snippets,
            test_framework,
            2, // retry attempt
            &truncate(error_output, 2000),
            &per_file_ctx,
        );
        let tier = claude::classify_repair_tier();

        if let Err(e) = self.run_ai(&prompt, &tier) {
            warn!("AI retry failed for {}: {} — discarding definitively", result.file, e);
            let _ = git::revert_changes(&self.config.path);
            return false;
        }

        // Verify no source files were modified
        let changed = match git::changed_files(&self.config.path) {
            Ok(f) => f,
            Err(e) => {
                warn!("Cannot check changed files after retry for {}: {}", result.file, e);
                let _ = git::revert_changes(&self.config.path);
                return false;
            }
        };

        if changed.is_empty() {
            warn!("No files changed during retry for {} — discarding", result.file);
            return false;
        }

        let source_modified: Vec<&String> = changed.iter()
            .filter(|f| !is_test_file(f) && !is_generated_artifact(f) && !is_internal_file(f))
            .collect();
        if !source_modified.is_empty() {
            warn!(
                "Source files modified during retry for {}: {:?} — reverting",
                result.file, source_modified
            );
            let _ = git::revert_changes(&self.config.path);
            return false;
        }

        let test_files: Vec<String> = changed.iter()
            .filter(|f| is_test_file(f))
            .cloned()
            .collect();
        if test_files.is_empty() {
            warn!("No test files generated during retry for {} — reverting", result.file);
            let _ = git::revert_changes(&self.config.path);
            return false;
        }

        // Build/compile retried tests
        let build_cmd = self.config.commands.test_compile.as_ref()
            .or(self.config.commands.build.as_ref());
        if let Some(cmd) = build_cmd {
            match runner::run_shell_command(&self.config.path, cmd, "test-compile") {
                Ok((true, _)) => {
                    info!("Retry build succeeded for {}", result.file);
                }
                Ok((false, output)) => {
                    warn!(
                        "Discarding test for {} — retry build also failed:\n{}",
                        result.file, runner::extract_error_summary(&output, 500)
                    );
                    let _ = git::revert_changes(&self.config.path);
                    return false;
                }
                Err(e) => {
                    warn!("Retry build error for {}: {} — discarding", result.file, e);
                    let _ = git::revert_changes(&self.config.path);
                    return false;
                }
            }
        }

        // Run tests on retried files
        match runner::run_tests(&self.config.path, test_framework, self.config.test_timeout) {
            Ok((true, _)) => {
                info!("Retry tests pass for {} — committing", result.file);
            }
            Ok((false, output)) => {
                warn!(
                    "Discarding test for {} — retry tests also failed:\n{}",
                    result.file, runner::extract_error_summary(&output, 500)
                );
                let _ = git::revert_changes(&self.config.path);
                return false;
            }
            Err(e) => {
                warn!("Retry test error for {}: {} — discarding", result.file, e);
                let _ = git::revert_changes(&self.config.path);
                return false;
            }
        }

        // Stage and commit
        let artifacts: Vec<String> = changed.iter()
            .filter(|f| is_generated_artifact(f))
            .cloned()
            .collect();
        let mut stage_refs: Vec<&str> = test_files.iter().map(|s| s.as_str()).collect();
        stage_refs.extend(artifacts.iter().map(|s| s.as_str()));
        if git::add_files(&self.config.path, &stage_refs).is_err() {
            warn!("Failed to stage retried files for {} — reverting", result.file);
            let _ = git::revert_changes(&self.config.path);
            return false;
        }
        let _ = git::revert_changes(&self.config.path); // clean non-test leftovers
        let msg = format_commit_message(
            &self.config, "test", "coverage",
            &format!("add tests for {} ({:.0}% → boost, retry)", result.file, result.coverage_before),
            "", "", &result.file,
        );
        if git::commit(&self.config.path, &msg).is_ok() {
            info!("Retry commit successful for {}", result.file);
            true
        } else {
            warn!("Retry commit failed for {} — reverting", result.file);
            let _ = git::revert_changes(&self.config.path);
            false
        }
    }

    /// Validate a wave of boost results and create a temporary "reparo-wip:" commit.
    ///
    /// Used when `commit_size > parallel_size`: multiple waves are accumulated as
    /// temporary commits and later squashed by [`squash_boost_commits`] into one
    /// real commit per `commit_size` files.
    ///
    /// Returns `(files_committed, source_file_list)`.
    fn validate_and_temp_commit_wave(
        &self,
        wave: &[BoostFileResult],
        test_framework: &str,
        stash_prefix: &str,
        run_tests: bool,
        framework_context: &str,
    ) -> Result<(usize, Vec<String>)> {
        if wave.is_empty() {
            return Ok((0, vec![]));
        }

        let file_names: Vec<&str> = wave.iter().map(|r| r.file.as_str()).collect();
        info!(
            "Validating wave of {} file(s) before temp commit: {}",
            wave.len(),
            file_names.join(", ")
        );

        // Pop all stashes from this wave
        let popped = git::stash_pop_matching(&self.config.path, stash_prefix)?;
        if popped == 0 {
            warn!("No stashes found for wave — skipping temp commit");
            return Ok((0, vec![]));
        }

        // Optionally run tests to validate wave files together
        if run_tests {
            // Build/compile before running tests (fast failure on compilation errors)
            let build_cmd = self.config.commands.test_compile.as_ref()
                .or(self.config.commands.build.as_ref());
            if let Some(cmd) = build_cmd {
                match runner::run_shell_command(&self.config.path, cmd, "test-compile") {
                    Ok((true, _)) => {
                        info!("Pre-test build succeeded for wave ({} files)", wave.len());
                    }
                    Ok((false, output)) => {
                        warn!(
                            "Pre-test build failed for {} files — falling back to per-file validation:\n{}",
                            wave.len(), runner::extract_error_summary(&output, 800)
                        );
                        let committed = self.fallback_per_file_commit(wave, test_framework, framework_context);
                        return Ok((committed, vec![]));
                    }
                    Err(e) => {
                        warn!("Pre-test build error during wave validation: {} — falling back to per-file validation", e);
                        let committed = self.fallback_per_file_commit(wave, test_framework, framework_context);
                        return Ok((committed, vec![]));
                    }
                }
            }

            match runner::run_tests(&self.config.path, test_framework, self.config.test_timeout) {
                Ok((true, _)) => {
                    info!("Wave tests pass ({} files)", wave.len());
                }
                Ok((false, output)) => {
                    warn!(
                        "Wave tests failed for {} files — falling back to per-file validation:\n{}",
                        wave.len(), runner::extract_error_summary(&output, 800)
                    );
                    let committed = self.fallback_per_file_commit(wave, test_framework, framework_context);
                    // Return empty files — fallback creates real commits, not temp wip commits
                    return Ok((committed, vec![]));
                }
                Err(e) => {
                    warn!("Test execution error during wave validation: {} — falling back to per-file validation", e);
                    let committed = self.fallback_per_file_commit(wave, test_framework, framework_context);
                    return Ok((committed, vec![]));
                }
            }
        }

        // Unstage everything (stash_pop_matching stages between applies),
        // then selectively re-stage only test files + artifacts.
        let _ = git::reset_index(&self.config.path);
        let mut all_stage_files: Vec<&str> = wave.iter()
            .flat_map(|r| r.test_files.iter().map(|s| s.as_str()))
            .collect();
        all_stage_files.extend(wave.iter().flat_map(|r| r.artifacts.iter().map(|s| s.as_str())));
        if let Err(e) = git::add_files(&self.config.path, &all_stage_files) {
            warn!("Failed to stage wave test files: {}", e);
            let _ = git::revert_changes(&self.config.path);
            return Ok((0, vec![]));
        }
        let _ = git::revert_changes(&self.config.path); // clean remaining leftovers

        // Create temp "reparo-wip:" commit — will be squashed later
        // Uses --no-verify to bypass pre-commit hooks (e.g. Conventional Commits)
        // since this is a temporary commit that will be squashed into a proper one.
        let wip_msg = format!(
            "reparo-wip: coverage boost {} file(s): {}",
            wave.len(),
            file_names.join(", ")
        );
        match git::commit_no_verify(&self.config.path, &wip_msg) {
            Ok(()) => {
                info!("Temp wave commit created ({} files) — pending squash", wave.len());
                Ok((wave.len(), wave.iter().map(|r| r.file.clone()).collect()))
            }
            Err(e) => {
                warn!("Failed to create temp wave commit: {} — reverting", e);
                let _ = git::revert_changes(&self.config.path);
                Ok((0, vec![]))
            }
        }
    }

    /// Squash N temporary "reparo-wip:" commits into a single real commit.
    ///
    /// Used when `commit_size > parallel_size`: after accumulating enough temp
    /// commits, this squashes them and creates one properly formatted commit.
    fn squash_boost_commits(&self, n: usize, files: &[String]) -> Result<()> {
        if n == 0 {
            return Ok(());
        }

        info!("Squashing {} temp commit(s) into one real commit ({} files)...", n, files.len());

        // Verify that the last n commits are "reparo-wip:" commits (safety check)
        let log_output = std::process::Command::new("git")
            .current_dir(&self.config.path)
            .args(["log", "--oneline", &format!("-{}", n)])
            .output();

        if let Ok(out) = log_output {
            let log_str = String::from_utf8_lossy(&out.stdout);
            let non_wip: Vec<&str> = log_str.lines()
                .filter(|l| !l.contains("reparo-wip:"))
                .collect();
            if !non_wip.is_empty() {
                warn!(
                    "Cannot squash: last {} commits contain non-wip entries: {:?}",
                    n, non_wip
                );
                return Ok(());
            }
        }

        // git reset --soft HEAD~n to unstage all wip commits back to index
        let reset_status = std::process::Command::new("git")
            .current_dir(&self.config.path)
            .args(["reset", "--soft", &format!("HEAD~{}", n)])
            .status();

        match reset_status {
            Ok(s) if s.success() => {}
            Ok(s) => {
                warn!("git reset --soft HEAD~{} failed (exit {})", n, s);
                return Ok(());
            }
            Err(e) => {
                warn!("Failed to run git reset: {}", e);
                return Ok(());
            }
        }

        // Create the real commit
        let file_list: Vec<&str> = files.iter().map(|s| s.as_str()).collect();
        let msg = if files.len() == 1 {
            format_commit_message(
                &self.config, "test", "coverage",
                &format!("add tests for {} (coverage boost)", files[0]),
                "", "", &files[0],
            )
        } else {
            format_commit_message(
                &self.config, "test", "coverage",
                &format!("add tests for {} files ({})", files.len(), file_list.join(", ")),
                "", "", "",
            )
        };

        match git::commit(&self.config.path, &msg) {
            Ok(()) => {
                info!("Squash commit successful ({} files in {} waves)", files.len(), n);
            }
            Err(e) => {
                warn!("Squash commit failed: {}", e);
            }
        }
        Ok(())
    }

    /// Run the coverage command and return the overall project coverage percentage.
    fn run_coverage_and_measure(&self, cov_cmd: &str) -> Option<f64> {
        let output_text = match runner::run_shell_command(&self.config.path, cov_cmd, "coverage measurement") {
            Ok((true, output)) => output,
            Ok((false, output)) => {
                warn!("Coverage command failed: {}", truncate(&output, 200));
                return None;
            }
            Err(e) => {
                warn!("Coverage command error: {}", e);
                return None;
            }
        };

        // Warn about common JaCoCo issues in the output
        if output_text.contains("Skipping JaCoCo execution due to missing execution data") {
            warn!(
                "JaCoCo skipped report generation — no execution data (jacoco.exec) was produced. \
                 This usually means tests did not run with the JaCoCo agent. \
                 Check that the Maven profile or surefire argLine is configured correctly in the coverage command."
            );
        }

        let lcov_path = runner::find_lcov_report_with_hint(&self.config.path, self.config.commands.coverage_report.as_deref())?;
        let overall = runner::overall_lcov_coverage(&lcov_path);
        if let Some(pct) = overall {
            color_info!("Project-wide test coverage: {}", cov_vs(pct, self.config.min_coverage));
        }
        overall
    }
}
